
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "mysql://root:admin@db/juniortest"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: juniortest
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
