apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: junior-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: juanda0191/junior-test-web:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "mysql://root:admin@db/juniortest"
